-- 2. Revenue by Doctor Specialization
-- Task: Calculate total revenue generated by each doctor specialization.
-- Challenge: Include percentage contribution of each specialization to total hospital revenue.

SELECT 
    d.specialization,
    ROUND(SUM(t.cost),2) AS specialization_revenue,
    ROUND(SUM(cost) / (SELECT 
            SUM(cost)
        FROM
            treatments) * 100,2)  AS persentage_contribution
FROM
    doctors d
        JOIN
    appointments a USING (doctor_id)
        JOIN
    treatments t USING (appointment_id)
GROUP BY specialization
ORDER BY persentage_contribution DESC